export const APP_DEFAULT_PORT = 3000;
export const SWAGGER_TITLE = 'PETSIS FINDER API DOCUMENTATION';
export const SWAGGER_DESCRIPTION = 'PETSIS FINDER API DOCUMENTATION';
export const GLOBAL_ROOT_PREFIX = 'api';
